{% set name = "buildbot-worker" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a485dda9a842589191897283ca2876523198772cf08719d880cc02cdd41f614a

build:
  number: 1
  entry_points:
    - buildbot-worker=buildbot_worker.scripts.runner:run
    - buildbot_worker_windows_service=buildbot_worker.scripts.windows_service:HandleCommandLine  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
  run:
    - future
    - python >3.5
    - twisted >=17.9.0

test:
  imports:
    - buildbot_worker
    - buildbot_worker.backports
    - buildbot_worker.commands
    - buildbot_worker.scripts
    - buildbot_worker.util
  commands:
    - buildbot-worker --help
    - pip check
  requires:
    - pip

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Buildbot worker daemon
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
