{% set name = "buildbot-worker" %}
{% set version = "3.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4c5ca606752e7ce11667f21429dee779b67eca5e7c642845906ad4c4e5e7dbc8

build:
  number: 0
  noarch: python
  entry_points:
    - buildbot-worker=buildbot_worker.scripts.runner:run
    - buildbot_worker_windows_service=buildbot_worker.scripts.windows_service: HandleCommandLine  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
  run:
    - future
    - python >3.5
    - twisted >=17.9.0

test:
  imports:
    - buildbot_worker.util
  commands:
    - buildbot-worker --help
  requires:
    - mock

about:
  home: https://buildbot.net/
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file: COPYING
  summary: Buildbot worker daemon
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
