{% set name = "buildbot-worker" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9610c0633b3340549dbb09a7fba208705233530e4e17e5082e1d1b6c8425be80

build:
  number: 1
  noarch: python
  entry_points:
    - buildbot-worker=buildbot_worker.scripts.runner:run
    - buildbot_worker_windows_service=buildbot_worker.scripts.windows_service: HandleCommandLine  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - future
    - python >={{ python_min }}
    - twisted >=17.9.0

test:
  imports:
    - buildbot_worker.util
  commands:
    - buildbot-worker --help
  requires:
    - mock
    - python {{ python_min }}

about:
  home: https://buildbot.net/
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file: COPYING
  summary: Buildbot worker daemon
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
