{% set name = "buildbot-worker" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66ca92917ab12b915c00d2f0794b854496c2d9e50deb0b6198efb3cd94219eef

build:
  number: 0
  python: noarch
  entry_points:
    - buildbot-worker=buildbot_worker.scripts.runner:run
    - buildbot_worker_windows_service=buildbot_worker.scripts.windows_service: HandleCommandLine  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
  run:
    - future
    - python >3.5
    - twisted >=17.9.0

test:
  imports:
    - buildbot_worker
    - buildbot_worker.backports
    - buildbot_worker.commands
    - buildbot_worker.monkeypatches
    - buildbot_worker.scripts
    - buildbot_worker.test
    - buildbot_worker.test.fake
    - buildbot_worker.test.unit
    - buildbot_worker.test.util
    - buildbot_worker.util
  commands:
    - buildbot-worker --help
  requires:
    - mock

about:
  home: https://buildbot.net/
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file: COPYING
  summary: Buildbot worker daemon
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
