travis:
  secure:
    BINSTAR_TOKEN: HUZdLW6mJ9oszWmYWS3b0z7srhvmRHSSI1FZkIpqXIaTjw9dhr0h9G4Scxz8+D9UQGxPUUwK/KP06g0MNYDDEgwCFW6xe+rhYYPabONp69uOM4kiRA2KQOaqbph/HB9zywh0A7gmOik1a0zK8Nyz+62K+zbmHWT7sxBRTv1kGHDR/N/eMw0EA8u+vOHoMSctLe2pL4KIrtXCQt6Wvk0CDdkcrt5p2CEC0u47GJlBMbxKWLaly7ga8IrmNSdoL7kY9mKFNSNBc9SAkgi82rjeXl6l7hreqpXKTVCtgGnmgxibrUkTF2HrvN7M01oMWalojOPvpUS97jNGX+xY5fTNxGzSiSDDcP51Oate+39XdgyVlwNqbHYwiga0pqtdUCpmQTbubKJb+P6YOHc5aa93M/TYZCoRhtLhL+xy7aSW3XlpiU4UcEVDyFXHSsRlajHzgKU01cs+uatTLUz+CuHAyerJ+hZK1LISuAEtobNeZuy85q3f404eM3xRn/yCZBr8hbKv7+BThpMMnaW7Qd1uPCYZe1zAYh1RD+M4n5cJYuIH2aM0dXHu41rc8AoOpgrijakShO3fBwI3ZgJg+mJd5MnBMyGsdsjuTzTpCQ+KHM8sNSVFKLHfblHQVZakQjNxfLqXZNxEHo6Q9oRj0Z33dVsNP4G70XZiuQC+5iWpXwk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
